trigger: none

pool:
 vmImage: ubuntu-latest

variables:
  bkstrgrg: 'rjn'
  bkstrg: 'rohit090909'
  bkcontainer: 'tfstate'
  bkstrgkey: 'key.tfstate'

stages:
  - stage: tfvalidate
    jobs: 
    - job: validate
      continueOnError: false
      steps:
         - task: TerraformInstaller@1
           displayName: tfinstall
           inputs:
              terraformVersion: 'latest'

         - task: TerraformTaskV4@4
           displayName: init
           inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: 'azure'
              backendAzureRmResourceGroupName: '$(bkstrgrg)'
              backendAzureRmStorageAccountName: '$(bkstrg)'
              backendAzureRmContainerName: '$(bkcontainer)'
              backendAzureRmKey: '$(key.tfstate)'
         - task: TerraformTaskV4@4
           displayName: validate
           inputs:
             provider: 'azurerm'
             command: 'validate'
  - stage: tfdeploy
    condition: succeeded(tfvalidate)
    dependsOn: tfvalidate
    jobs:
      - job: apply
        steps:
          - task: TerraformInstaller@1
            displayName: tfinstall
            inputs:
              terraformVersion: 'latest'

          - task: TerraformTaskV4@4
            displayName: init
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: 'azure'
              backendAzureRmResourceGroupName: '$(bkstrgrg)'
              backendAzureRmStorageAccountName: '$(bkstrg)'
              backendAzureRmContainerName: '$(bkcontainer)'
              backendAzureRmKey: '$(key.tfstate)'
          - task: TerraformTaskV4@4
            displayName: plan          
            inputs:
              provider: 'azurerm'
              command: 'plan'
              environmentServiceNameAzureRM: 'azure'
          - task: TerraformTaskV4@4
            displayName: apply
            inputs:
              provider: 'azurerm'
              command: 'apply'
              environmentServiceNameAzureRM: 'azure'
  
